# Custom Language File for Launcher Customizer

[ejs.app]
title = "Eryndor RP Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/sunl1nx/EryndorLauncher"
mediaTwitterURL = "https://x.com/sunl1nx"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@Sunl1nx"
mediaDiscordURL = "https://discord.gg/56XCPQQpbW"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/Sunl1nx/EL/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR ERYNDOR RP"
welcomeDescription = "Eryndor est un Network RP créer par : Sunl1nx, Ca.mz et Yuki"
welcomeDescCTA = "Nous avons hate de vous accueillir au sein de notre infrastructure."

[js.landing.discord]
loading = "Chargement du jeu.."
joining = "Réveil en cours..."
joined = "Sujet réveilé"
